#!/bin/sh

# エラー停止の設定
set -euo pipefail

export PATH="/opt/awscli/bin:${PATH}"
export PYTHONPATH="/opt//awscli/lib/python2.7/site-packages"

# ハンドラー関数を読み込み
source $LAMBDA_TASK_ROOT/"$(echo $_HANDLER | cut -d. -f1).sh"

# ループ処理
while true
do
    HEADERS="$(mktemp)"
    # イベントを取得
    EVENT_DATA=$(curl -sS -LD "$HEADERS" -X GET "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")
    # リクエストIDを取得
    REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    # ハンドラー関数を実行
    RESPONSE=$($(echo "$_HANDLER" | cut -d. -f2) "$EVENT_DATA")

    # レスポンスを返す
    curl -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" -d "$RESPONSE"
done